version: "3.7"

services:

  html:
    image: didierjulien/phpweb:7.2
    container_name: WP_Local_PHP
    ports:
      - "2080:80"
      - "2443:443"
    volumes:
      - ./html:/var/www/html:cached
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./conf/web/apache2.conf:/etc/apache2/apache2.conf:cached
      - ./conf/web/000-default.conf:/etc/apache2/sites-available/000-default.conf:cached

    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: dbdata
      WORDPRESS_DB_PASSWORD: dbdata

  mysql:
    image: mysql:5.7.27
    container_name: WP_Local_DB
    expose:
      - "3306"
    volumes:
      - ./sql/data:/var/lib/mysql:delegated
      - ./conf/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:cached
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbdata
      MYSQL_DATABASE: dbdata
      MYSQL_USER: dbdata
      MYSQL_PASSWORD: dbdata

  # adminer:
  #   image: adminer
  #   container_name: WP_Local_ADMINER
  #   restart: always
  #   volumes:
  #     - ./conf/php/php.ini:/usr/local/etc/php/php.ini:cached
  #   ports:
  #     - "2386:8080"

  # node:
  #   image: didierjulien/nodejs:12
  #   user: "node"
  #   container_name: WP_Local_Node
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=local
  #   volumes:
  #     - ./html/wp-content/themes/custom:/home/node/app:cached
  #   expose:
  #     - "8081"
  #   command: bash -c "yarn install && bower install --allow-root && gulp"

volumes:
    sql:
    html:
    conf:
